import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BackgroundDecorations from "./components/Share/BackgroundDecorations";
import Navbar from "./Navbar/Navbar";
import Footer from "./Footer/Footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Travel Website",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative min-h-screen">
          {/* Decorations in background */}
          <BackgroundDecorations/>
          {/* Main Content */}
          <Navbar/>
          <div className="relative z-10">{children}</div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
